### ISSUE TITLE
aways Initialization,how to use it??

### ISSUE THREAD

**Issue by blover2009** [Tom60chat/Microsoft-Rewards-Farmer-Sharp#140] opened 2023-04-01 13:04 UTC
For qestion, please visit the Discord server.
Log 
Microsoft Rewards Farmer by Tom Olivier                                  Version 0.10.1.0 (Checking for new versions...)

Log 
[0](0/0) - 0 points: Pending...

Log 
[0](0/6) - 0 points: Initialization...

Log 
Microsoft Rewards Farmer by Tom Olivier                                                Version 0.10.1.0 (Latest version)

Exception 0: Farmer
PuppeteerSharp.WaitTaskTimeoutException: waiting for selector '#microsoft' failed: timeout 300000 ms exceeded
   at PuppeteerSharp.DOMWorld.WaitForSelectorInPageAsync(String queryOne, String selector, WaitForSelectorOptions options, PageBinding[] bindings) in C:\projects\puppeteer-sharp\lib\PuppeteerSharp\DOMWorld.cs:line 354
   at PuppeteerSharp.CustomQueriesManager.<>c__DisplayClass13_0.<<MakeQueryHandler>b__1>d.MoveNext() in C:\projects\puppeteer-sharp\lib\PuppeteerSharp\CustomQueriesManager.cs:line 159
--- End of stack trace from previous location ---
   at PuppeteerSharp.DOMWorld.WaitForSelectorAsync(String selector, WaitForSelectorOptions options) in C:\projects\puppeteer-sharp\lib\PuppeteerSharp\DOMWorld.cs:line 498
   at PuppeteerSharp.Frame.WaitForSelectorAsync(String selector, WaitForSelectorOptions options) in C:\projects\puppeteer-sharp\lib\PuppeteerSharp\Frame.cs:line 115
   at MicrosoftRewardsFarmer.Farmer.ConnectToMicrosoft(IPage page, Session session, Account account, IProgress`1 progress) in /home/tom/Documents/Projets/Logiciels/Microsoft-Rewards-Farmer-Sharp/Microsoft Rewards Farmer/Farmer.cs:line 154
   at MicrosoftRewardsFarmer.Farmer.StartAsync(IProgress`1 progress) in /home/tom/Documents/Projets/Logiciels/Microsoft-Rewards-Farmer-Sharp/Microsoft Rewards Farmer/Farmer.cs:line 92
   at MicrosoftRewardsFarmer.Farmer.StartAsync(IProgress`1 progress) in /home/tom/Documents/Projets/Logiciels/Microsoft-Rewards-Farmer-Sharp/Microsoft Rewards Farmer/Farmer.cs:line 120
   at MicrosoftRewardsFarmer.TUI.Program.<>c.<<StartFarming>b__4_0>d.MoveNext() in /home/tom/Documents/Projets/Logiciels/Microsoft-Rewards-Farmer-Sharp/Microsoft Rewards Farmer.TUI/Program.cs:line 125

Exception 
[0](0/0) - 0 points: [Exception] Farmer - waiting for selector '#microsoft' failed: timeout 300000 ms exceeded
The invitation link is available at https://github.com/Tom60chat/Microsoft-Rewards-Farmer-Sharp.

**Comment by Tom60chat** [comment] 2023-05-20 14:52
Duplicate of #104

**Closed by Tom60chat** 2023-05-20 14:52 UTC
