### ISSUE TITLE
[Exception] System.IO.IOException  when using more than 2 accounts

### ISSUE THREAD

**Issue by CrazyLight21** [Tom60chat/Microsoft-Rewards-Farmer-Sharp#131] opened 2023-03-23 08:11 UTC
**Describe the bug**
It crashes when using more than 2 accounts with more than 2 accounts it crashes. works 100%of time with 2 accounts

**To Reproduce**
it is very easy to reproduce:
1. just use 3 or more  accounts
2. See error

**Expected behavior**
It is going to crash
**additional note**
I don't know about other OS but this bug occurs on windows 10 32bit or
maybe if this is a ram or processor related  issue, I have 2gb ram and a atom z3775 processor

![bug](https://user-images.githubusercontent.com/128027767/227141797-97602b88-d7aa-487c-9542-084bf7a87e1e.png)

**Comment by Tom60chat** [comment] 2023-05-20 14:42
Duplicate of #119

**Closed by Tom60chat** 2023-05-20 14:42 UTC
Labels: bug
