### ISSUE TITLE
DISCORD SERVER BANNED

### ISSUE THREAD

**Issue by Skewter** [Tom60chat/Microsoft-Rewards-Farmer-Sharp#173] opened 2023-06-01 17:43 UTC
Sorry for the clickbait:)
I had seen the stable versions photo of tom's farmer bot that are best to work with.
i was going to download today but the server is slammed today.
please share the stable versions or at least that photo of stable versions...please.
which one are the good version to download that work well?

**Comment by Tom60chat** [comment] 2023-06-02 07:08
Well, duplicate of #172 
And you can read the front page that should have all the basic info.

I'm going to publish to #172, some info exclusive to the discord server.

**Closed** 2023-06-02 07:08 UTC
Labels: duplicate
