### ISSUE TITLE
Stuck at Getting Cards

### ISSUE THREAD

**Issue by fabarzy** [Tom60chat/Microsoft-Rewards-Farmer-Sharp#29] opened 2022-11-30 14:23 UTC
Starting today, the script is stuck at "Getting Cards" on all of my accounts.  I've rebooted and tried both MFA and non-MFA accounts with the same results.  I starting seeing this in build 0.8 this morning but same result  after updating to 0.82

**Comment by Tom60chat** [comment] 2022-11-30 14:26
Hello,
Thanks for your feddback.

The problem is similar to https://github.com/Tom60chat/Microsoft-Rewards-Farmer-Sharp/issues/24.
I recommend you to use version 0.7.1, while the problem is being solved.

**Comment by fabarzy** [comment] 2022-11-30 14:35
Thanks for the quick response!  I just tried version 0.71 with the same results.  I did run it in interactive mode so I can see what's happening in the browser and it seems like it's just constantly refreshing the page after a successful login.

**Comment by Tom60chat** [comment] 2022-11-30 14:48
Hmm, looks like an old bug.

Can you share with me the last log file in the logs folder?

**Comment by fabarzy** [comment] 2022-11-30 14:57
[2022-11-30 08.03.36.txt](https://github.com/Tom60chat/Microsoft-Rewards-Farmer-Sharp/files/10124330/2022-11-30.08.03.36.txt)

See attached.  I replaced my account names with generic labels for privacy reasons.  Also, I did have a Chrome update install this morning which might be the cause.  I was at Chrome version 107 but now I'm showing it's:  Version 108.0.5359.72 (Official Build) (64-bit)

**Comment by Tom60chat** [comment] 2022-11-30 15:21
I don't know if the Chrome update can break the application.

Just out of curiosity, if you delete the Session folder (if it is not empty), does it change anything?

**Comment by fabarzy** [comment] 2022-11-30 15:51
I did try deleting the sessions folder earlier on version 0.8 which didn't work.  I just tried 0.82 with the same result.  On version 0.71, I don't see any sessions folders at all, just a runtimes folder.

**Comment by Tom60chat** [comment] 2022-11-30 16:15
Well, this issue needs further investigations, it will take some time for the issue to be solved.

**Comment by fabarzy** [comment] 2022-11-30 16:25
Understood and no rush.  Please let me know if I can help with testing or anything else.

**Comment by fabiovieitas** [comment] 2022-11-30 18:48
Here occurs same situation....

**Comment by AdicoS99** [comment] 2022-12-01 10:52
Same problem goes for me.

**Comment by namimama** [comment] 2022-12-01 12:57
> Hello, Thanks for your feddback.
> 
> The problem is similar to #24. I recommend you to use version 0.7.1, while the problem is being solved.

in the 0.7.1 is the same problem "Getting Cards"

**Comment by Tom60chat** [comment] 2022-12-01 13:12
Hello everyone,

Quick question: what version of chrome/chromium have you ?

**Comment by fabiovieitas** [comment] 2022-12-01 13:20
> Olá a todos,
> 
> Pergunta rápida: que versão do cromo / cromo você tem?

Versão 108.0.5359.72 (Versão oficial) 64 bits

**Comment by AdicoS99** [comment] 2022-12-01 15:15
> Hello everyone,
> 
> Quick question: what version of chrome/chromium have you ?

108.0.5359.72 (Build ufficiale) (a 64 bit)

**Comment by Raven-Sus** [comment] 2022-12-01 15:19
> Hello everyone,
> 
> Quick question: what version of chrome/chromium have you ?

Version 108.0.5359.72 (Official Build) (64-bit)

**Comment by Tom60chat** [comment] 2022-12-01 15:27
Thank you all.

This doesn't seam to be a chrome/chromium version problem.

**Comment by Raven-Sus** [comment] 2022-12-01 15:27
> Hello everyone,
> 
> Quick question: what version of chrome/chromium have you ?

Version 108.0.5359.72 (Official Build) (64-bit)

**Comment by namimama** [comment] 2022-12-01 16:03
> i, i don't have Chrome installed, my chromium is Versão 93.0.4577.0 (Compilação de programador) (64 bits)

nothing, we're glad to help.

**Comment by namimama** [comment] 2022-12-01 16:03
> Obrigado a todos.
> 
> Isso não parece ser um problema de versão cromo / cromo.

nothing, we're glad to help

**Comment by fabiovieitas** [comment] 2022-12-01 17:03
We count on the solution a lot.  Note: I will make a small donation for all care.

Português -

Contamos muito com a solução. Obs.: farei uma pequena doação por todo cuidado.

**Comment by Tom60chat** [comment] 2022-12-01 19:50
I was able to reproduce the problem on my end.

I think Microsoft changed something that completely broke the application.
I might fix the issue this weekend.

**Comment by namimama** [comment] 2022-12-01 20:13
> I was able to reproduce the problem on my end.
> 
> I think Microsoft changed something that completely broke the application. I might fix the issue this weekend.

Ok, looking forward to it

**Comment by Tom60chat** [comment] 2022-12-04 14:15
Hello everyone,

I am glad to share with you the new version of MRF:
https://github.com/Tom60chat/Microsoft-Rewards-Farmer-Sharp/releases/tag/v0.9.0

I hope I could solve most of the problems.


@fabarzy  If the issue was fixed in your side, feel free to close the issue.

**Comment by fabarzy** [comment] 2022-12-05 01:43
Back up and running over here.  Thanks so much for your hard work!

**Closed** 2022-12-05 01:43 UTC
Labels: bug
