### ISSUE TITLE
Can't run the program

### ISSUE THREAD

**Issue by zd001** [Tom60chat/Microsoft-Rewards-Farmer-Sharp#35] opened 2022-12-12 06:43 UTC
![image](https://user-images.githubusercontent.com/49865538/206978356-0f618632-582c-4156-8029-48328ab50be6.png)

**Comment by Tom60chat** [comment] 2022-12-12 07:05
Hello, thanks for the feesback.

Are you using the version 0.9 or 0.9.1 ?

**Comment by fabiovieitas** [comment] 2022-12-12 12:37
I believe the netframework is missing

**Comment by zd001** [comment] 2022-12-12 12:40
The version is v0.90,and I just found out that the project has been updated to version 0.91, but an error is still reported after running,
![image](https://user-images.githubusercontent.com/49865538/207047614-8dc3b85e-d167-47c1-b85b-b1e4864e2b63.png)

**Comment by zd001** [comment] 2022-12-12 14:10
sure,it's the complete message

Unhandled exception. System.ArgumentException: The NeutralResourcesLanguageAttri
bute on the assembly "Microsoft Rewards Farmer, Version=0.9.1.0, Culture=neutral
, PublicKeyToken=null" specifies an invalid culture name: "en-150".
 ---> System.Globalization.CultureNotFoundException: Culture is not supported. (
Parameter 'name')
en-150 is an invalid culture identifier.
   at System.Globalization.CultureInfo.GetCultureInfo(String )
   at System.Resources.ManifestBasedResourceGroveler.GetNeutralResourcesLanguage
(Assembly , UltimateResourceFallbackLocation& )
   --- End of inner exception stack trace ---
   at System.Resources.ManifestBasedResourceGroveler.GetNeutralResourcesLanguage
(Assembly , UltimateResourceFallbackLocation& )
   at System.Resources.ResourceManager.CommonAssemblyInit()
   at System.Resources.ResourceManager..ctor(String , Assembly )
   at MicrosoftRewardsFarmer.Resources.Main.get_ResourceManager() in C:\Users\To
m60\Nextcloud2\Documents\Projects\dotnet\Microsoft Rewards Farmer\MicrosoftRewar
ds-Farmer\Resources\Main.Designer.cs:line 42
   at MicrosoftRewardsFarmer.Resources.Main.get_Checking_version() in C:\Users\T
om60\Nextcloud2\Documents\Projects\dotnet\Microsoft Rewards Farmer\MicrosoftRewa
rds-Farmer\Resources\Main.Designer.cs:line 86
   at MicrosoftRewardsFarmer.Program.DrawHeader() in C:\Users\Tom60\Nextcloud2\D
ocuments\Projects\dotnet\Microsoft Rewards Farmer\MicrosoftRewards-Farmer\Progra
m.cs:line 82
   at MicrosoftRewardsFarmer.Program.StartFarming() in C:\Users\Tom60\Nextcloud2
\Documents\Projects\dotnet\Microsoft Rewards Farmer\MicrosoftRewards-Farmer\Prog
ram.cs:line 67
   at MicrosoftRewardsFarmer.Program.Main(String[] args) in C:\Users\Tom60\Nextc
loud2\Documents\Projects\dotnet\Microsoft Rewards Farmer\MicrosoftRewards-Farmer
\Program.cs:line 35


![image](https://user-images.githubusercontent.com/49865538/207066442-cdf06d62-2af0-448c-9be1-cf11eb224ed6.png)

**Comment by Tom60chat** [comment] 2022-12-12 14:14
Okay, I spot the error, I will fix that on the next version.

The NeutralLanguage inside Microsoft Rewards Farmer.csproj is not correct.

**Comment by Tom60chat** [comment] 2022-12-16 15:33
Hello back,

The version [0.9.2-beta1](https://github.com/Tom60chat/Microsoft-Rewards-Farmer-Sharp/releases/tag/v0.9.2-beta1) has been release.

Let me know if your issue has been fixed.

**Comment by zd001** [comment] 2022-12-17 06:00
Hi, it looks like it works. But the program will stop running due to various reasons.

Is it because of my local environment?





Microsoft Rewards Farmer by Tom Olivier         Version 0.9.2.0 (Latest version)

[*******](3/6) - 3967 points: Running desktop searches 46/50

[*******](2/6) - 3535 points: [Exception] Farmer - Timeout of
30000 ms exceeded
[*******](2/6) - 3722 points: Getting cards...

[*******](2/6) - 3300 points: [Exception] Farmer - Node is
either not visible or not an HTMLElement
[*******](2/6) - 3508 points: [Exception] Farmer - Node is
either not visible or not an HTMLElement

**Comment by Tom60chat** [comment] 2022-12-17 15:03
This may be because your version of Microsoft Rewards is too different from our version.

The problem is that I don't have a VPN to test your version in your country, so I don't think I can fix the bug.

**Comment by zd001** [comment] 2022-12-18 05:19
Because I used a vpn to complete the rewards in the US region, so it should not be due to the country I am in.

I ran it again and everything worked fine. It may be because the network speed is too slow and the reward page is not fully opened.

**Comment by Tom60chat** [comment] 2023-01-07 17:14
It seem your issue has been fixed, I'm closing the issue.

**Closed by Tom60chat** 2023-01-07 17:14 UTC
Labels: bug
