### ISSUE TITLE
The bot only gains 48 out of 90 points from PC researches

### ISSUE THREAD

**Issue by AdicoS99** [Tom60chat/Microsoft-Rewards-Farmer-Sharp#28] opened 2022-11-29 08:39 UTC

**Comment by Tom60chat** [comment] 2022-11-29 09:42
Hello,
Thanks for your feddback.

The problem is similar to #24.
I recommend you to use version 0.7.1, while the problem is being solved.

**Comment by AdicoS99** [comment] 2022-12-01 10:54
The 0.7.1 version does not work for me, when I click on the app nothing happens, am I missing something?

**Comment by Tom60chat** [comment] 2022-12-03 11:24
On #22 someone have the same issue as you.

**Comment by Tom60chat** [comment] 2022-12-04 14:16
Hello @AdicoS99 ,

I am glad to share with you the new version of MRF:
https://github.com/Tom60chat/Microsoft-Rewards-Farmer-Sharp/releases/tag/v0.9.0

I hope I could solve most of the issues.

If the issue was fixed in your side, feel free to close the issue.

**Comment by AdicoS99** [comment] 2022-12-05 08:56
Problem still persists, but it's the same as #31 so I'll close this one.

**Closed** 2022-12-05 08:57 UTC
Labels: bug
