### ISSUE TITLE
System.AggregateException: One or more errors occurred. (CodeBase is not supported on assemblies loaded from a single-file bundle.)

### ISSUE THREAD

**Issue by Jiu-Ling** [Tom60chat/Microsoft-Rewards-Farmer-Sharp#133] opened 2023-03-24 11:20 UTC
The lastest version 0.10.1-beta1 on Centos 7 x64:
Unhandled exception.
System.AggregateException: One or more errors occurred. (CodeBase is not supported on assemblies loaded from a single-file bundle.)
 ---> System.NotSupportedException: CodeBase is not supported on assemblies loaded from a single-file bundle.
   at System.Reflection.RuntimeAssembly.get_CodeBase()
   at PuppeteerSharp.BrowserFetcher.GetExecutablePath() in C:\projects\puppeteer-sharp\lib\PuppeteerSharp\BrowserFetcher.cs:line 356
   at PuppeteerSharp.BrowserFetcher..ctor() in C:\projects\puppeteer-sharp\lib\PuppeteerSharp\BrowserFetcher.cs:line 53
   at PuppeteerPlus.Utility.TryGetBuildInBrowser(String& browserPath) in /home/tom/Documents/Projets/Logiciels/Microsoft-Rewards-Farmer-Sharp/Puppeteer Plus/Utility.cs:line 129
   at MicrosoftRewardsFarmer.Utilities.PuppeteerPlusUtility.GetBrowserAsync() in /home/tom/Documents/Projets/Logiciels/Microsoft-Rewards-Farmer-Sharp/Microsoft Rewards Farmer/Utilities/PuppeteerPlusUtility.cs:line 34
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean )
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean )
   at System.Threading.Tasks.Task`1.get_Result()
   at MicrosoftRewardsFarmer.TUI.Program.StartFarming() in /home/tom/Documents/Projets/Logiciels/Microsoft-Rewards-Farmer-Sharp/Microsoft Rewards Farmer.TUI/Program.cs:line 90
   at MicrosoftRewardsFarmer.TUI.Program.Main(String[] args) in /home/tom/Documents/Projets/Logiciels/Microsoft-Rewards-Farmer-Sharp/Microsoft Rewards Farmer.TUI/Program.cs:line 60

Press any key to exit.

**Comment by jackjack21-pixel** [comment] 2023-03-28 16:56
It looks like you’re encountering an error while running the Microsoft Rewards Farmer Sharp program on CentOS 7 x64. The error message suggests that there is an issue with the CodeBase property not being supported on assemblies loaded from a single-file bundle.

This issue could be related to the version of .NET that you’re using. You could try updating to the latest version of .NET to see if that resolves the issue.

**Comment by Jiu-Ling** [comment] 2023-04-01 16:23
> It looks like you’re encountering an error while running the Microsoft Rewards Farmer Sharp program on CentOS 7 x64. The error message suggests that there is an issue with the CodeBase property not being supported on assemblies loaded from a single-file bundle.
> 
> This issue could be related to the version of .NET that you’re using. You could try updating to the latest version of .NET to see if that resolves the issue.

I've tried to install .NET5.0/6.0/7.0, but it doesn't seem useful, the error occured again.

**Comment by Tom60chat** [comment] 2023-05-20 08:46
Duplicate of #126

**Closed by Tom60chat** 2023-05-20 08:46 UTC
Labels: bug
