### ISSUE TITLE
Appears when I execute on Windows 11

### ISSUE THREAD

**Issue by BigYty** [Tom60chat/Microsoft-Rewards-Farmer-Sharp#107] opened 2023-03-15 12:24 UTC
Unhandled exception. System.AggregateException: One or more errors occurred. (CodeBase is not supported on assemblies loaded from a single-file bundle.)
 ---> System.NotSupportedException: CodeBase is not supported on assemblies loaded from a single-file bundle.
   at System.Reflection.RuntimeAssembly.get_CodeBase()
   at PuppeteerSharp.BrowserFetcher.GetExecutablePath() in C:\projects\puppeteer-sharp\lib\PuppeteerSharp\BrowserFetcher.cs:line 356
   at PuppeteerSharp.BrowserFetcher..ctor() in C:\projects\puppeteer-sharp\lib\PuppeteerSharp\BrowserFetcher.cs:line 53
   at PuppeteerPlus.Utility.TryGetBuildInBrowser(String& browserPath) in /home/tom/Documents/Projets/Logiciels/Microsoft-Rewards-Farmer-Sharp/Puppeteer Plus/Utility.cs:line 129
   at MicrosoftRewardsFarmer.Utilities.PuppeteerPlusUtility.GetBrowserAsync() in /home/tom/Documents/Projets/Logiciels/Microsoft-Rewards-Farmer-Sharp/Microsoft Rewards Farmer/Utilities/PuppeteerPlusUtility.cs:line 34
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean )
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean )
   at System.Threading.Tasks.Task`1.get_Result()
   at MicrosoftRewardsFarmer.TUI.Program.StartFarming() in /home/tom/Documents/Projets/Logiciels/Microsoft-Rewards-Farmer-Sharp/Microsoft Rewards Farmer.TUI/Program.cs:line 74
   at MicrosoftRewardsFarmer.TUI.Program.Main(String[] args) in /home/tom/Documents/Projets/Logiciels/Microsoft-Rewards-Farmer-Sharp/Microsoft Rewards Farmer.TUI/Program.cs:line 53

**Comment by BigYty** [comment] 2023-03-15 12:24
[v0.10.0-beta1](https://github.com/Tom60chat/Microsoft-Rewards-Farmer-Sharp/releases/tag/v0.10.0-beta1)

**Comment by Tom60chat** [comment] 2023-03-15 12:26
Duplicate of #103

**Closed by Tom60chat** 2023-03-15 12:26 UTC
Labels: bug
