### ISSUE TITLE
Emails with same username but different domain names will be considered as one account.

### ISSUE THREAD

**Issue by Durian-p** [Tom60chat/Microsoft-Rewards-Farmer-Sharp#169] opened 2023-05-13 16:56 UTC
**Describe the bug**
Version 0.10.0.1
Email with same username but different domain names will be treated as one account.
eg.  abc@gmail.com and abc@163.com will be  considered as one account.

**To Reproduce**
1. Go to 'settings.json'
2. Config 2 accounts with same username but different domain
3. Run the program
4. Find 2 identical outputs from 2 different account (I am sure that those accounts have different amount of points)

**Expected behavior**
2 Microsoft account should be considered different.

**Screenshots**
![image](https://github.com/Tom60chat/Microsoft-Rewards-Farmer-Sharp/assets/88613370/644ff660-6776-4e2a-a157-5ff81ebd8b48)
![image](https://github.com/Tom60chat/Microsoft-Rewards-Farmer-Sharp/assets/88613370/c769ac34-8be0-4f47-ae45-9a43ff1a2a8b)

**Additional context**
There is only one profile folder in Profiles/ for those 2 accounts.
I tried to add -ns to disable session to fix it but it won't work.

**Comment by Tom60chat** [comment] 2023-05-20 15:38
Nice issue, but duplicate of #98

**Closed by Tom60chat** 2023-05-20 15:38 UTC
Labels: bug
