### ISSUE TITLE
[Exception] Farmer 

### ISSUE THREAD

**Issue by fabiovieitas** [Tom60chat/Microsoft-Rewards-Farmer-Sharp#116] opened 2023-03-17 01:58 UTC
Goodnight. Constant error for those who use VPN.

10.1 version

[Exception] Farmer - waiting for selector '#microsoft' failed: timeout
300000 ms exceeded                

Obs.: 0.9.1 does not occur these errors..

![image](https://user-images.githubusercontent.com/73303693/225791011-6fef3e8b-8d9f-4b1e-aba7-ac2c65304c74.png)

**Comment by Tom60chat** [comment] 2023-03-17 16:30
Nice, but duplicate of #104

**Closed by Tom60chat** 2023-03-17 16:30 UTC
Labels: bug
