### ISSUE TITLE
   Version9.20,9.30  today , [Exception] Farmer - Evaluation failed: ReferenceError: _w is not defined   

### ISSUE THREAD

**Issue by blover2009** [Tom60chat/Microsoft-Rewards-Farmer-Sharp#141] opened 2023-04-01 13:07 UTC
[Log] 
§cMicrosoft §aRewards §bFarmer §eby §rTom Olivier                                   Version 0.9.3.0 (Checking for new versions...)

[Log] 
§cMicrosoft §aRewards §bFarmer §eby §rTom Olivier                                    Version 0.9.3.0 (A new version is available!)

[Log] 
[0](0/6) - 0 points: Sign In...

[Log] 
[0](1/6) - 0 points: Obtaining the number of current reward points...

[Log] 
[0](2/6) - 0 points: Getting cards...

[Log] 
[0](2/6) - 0 points: Card processing 0 / 10

[Log] 
[0](2/6) - 0 points: Card processing 1 / 10

[Log] 
[0](2/6) - 0 points: Card processing 2 / 10

[Log] 
[0](2/6) - 0 points: Card processing 3 / 10

[Log] 
[0](2/6) - 0 points: Card processing 4 / 10

[Log] 
[0](2/6) - 0 points: Card processing 5 / 10

[Log] 
[0](2/6) - 0 points: Card processing 6 / 10

[Log] 
[0](2/6) - 0 points: Card processing 7 / 10

[Log] 
[0](2/6) - 0 points: Card processing 8 / 10

[Exception] 0: Farmer
PuppeteerSharp.EvaluationFailedException: Evaluation failed: ReferenceError: _w is not defined
    at __puppeteer_evaluation_script__:1:10
   at PuppeteerSharp.ExecutionContext.ExecuteEvaluationAsync(String method, Object args) in C:\projects\puppeteer-sharp\lib\PuppeteerSharp\ExecutionContext.cs:line 141
   at PuppeteerSharp.ExecutionContext.RemoteObjectTaskToObject[T](Task`1 remote) in C:\projects\puppeteer-sharp\lib\PuppeteerSharp\ExecutionContext.cs:line 95
   at PuppeteerSharp.DOMWorld.EvaluateFunctionAsync[T](String script, Object[] args) in C:\projects\puppeteer-sharp\lib\PuppeteerSharp\DOMWorld.cs:line 276
   at MicrosoftRewardsFarmer.TheFarm.MsRewards.ProceedQuizCardAsync(IPage card_page, String selector) in C:\Users\Tom60\Nextcloud\Documents\Projects\dotnet\Microsoft Rewards Farmer\MicrosoftRewards-Farmer\TheFarm\MsRewards.cs:line 333
   at MicrosoftRewardsFarmer.TheFarm.MsRewards.ProceedCardAsync(IPage cardPage) in C:\Users\Tom60\Nextcloud\Documents\Projects\dotnet\Microsoft Rewards Farmer\MicrosoftRewards-Farmer\TheFarm\MsRewards.cs:line 283
   at MicrosoftRewardsFarmer.TheFarm.MsRewards.ProceedCardsAsync(IElementHandle[] cardsElement) in C:\Users\Tom60\Nextcloud\Documents\Projects\dotnet\Microsoft Rewards Farmer\MicrosoftRewards-Farmer\TheFarm\MsRewards.cs:line 183
   at MicrosoftRewardsFarmer.TheFarm.Farmer.FarmPointsAsync(Int32 farmer_id, String browserPath) in C:\Users\Tom60\Nextcloud\Documents\Projects\dotnet\Microsoft Rewards Farmer\MicrosoftRewards-Farmer\TheFarm\Farmer.cs:line 169

[Log] 
[0](2/6) - 0 points: [Exception] Farmer - Evaluation failed: ReferenceError: _w is not defined
    at __puppeteer_evaluation_script__:1:10

**Comment by Tom60chat** [comment] 2023-04-05 22:07
You using an outdated version of MRF please use v0.10
duplicate of #55

**Closed by Tom60chat** 2023-04-05 22:07 UTC
