### ISSUE TITLE
Get points from QUESTS & PUNCH CARDS

### ISSUE THREAD

**Issue by KendallDoesCoding** [Tom60chat/Microsoft-Rewards-Farmer-Sharp#134] opened 2023-03-24 16:50 UTC
It should get points from Quests and Punch Cards.

EG: 
![image](https://user-images.githubusercontent.com/84712013/227589649-b2d5be46-8c42-4d98-82fe-7923f1e01a5b.png)

**Comment by Tom60chat** [comment] 2023-05-20 14:37
Duplicate of #45

**Closed by Tom60chat** 2023-05-20 14:37 UTC
