### ISSUE TITLE
v0.9.3-beta1

### ISSUE THREAD

**Issue by Checkra2n** [Tom60chat/Microsoft-Rewards-Farmer-Sharp#99] opened 2023-03-09 14:53 UTC
system: win10 x64
I  use  VPN（clash Tun mode），it prompts error:
 [Exception] Farmer - Evaluation failed: ReferenceError: _w is not defined
   at __puppeteer_evaluation_script__:1:10ion] Farmer - Evaluation failed: ReferenceError: _w is not
defined
 at __puppeteer_evaluation_script__:1:10] Farmer - Evaluation failed: ReferenceError: _w is not
defined
[](url)

**Comment by Checkra2n** [comment] 2023-03-09 15:01
https://imgloc.com/i/o2RKH

**Comment by Tom60chat** [comment] 2023-03-09 16:12
Duplicate of #55

**Closed by Tom60chat** 2023-03-09 16:12 UTC
Labels: bug
