### ISSUE TITLE
[Exception] Farmer - Can't sign in to Microsoft Rewards

### ISSUE THREAD

**Issue by 12189108** [Tom60chat/Microsoft-Rewards-Farmer-Sharp#72] opened 2023-02-08 10:51 UTC
In China, the app doesn't work properly, it's only available through a VPN, and I don't quite know which step went wrong.

**Comment by Tom60chat** [comment] 2023-02-08 10:53
Hello, You can start in head mode -nh, to figure out what go wrong during the Sign In process.

**Comment by 12189108** [comment] 2023-02-08 11:08
> Hello, You can start in head mode -nh, to figure out what go wrong during the Sign In process.

It says "Misrosoft Rewards is not available in this country or region." .But I also don't use a VPN, and I don't have this prompt when accessing https://rewards.bing.com/.
![捕获](https://user-images.githubusercontent.com/24732116/217512839-fadb7da3-c85d-41d7-968a-f3773940a6cb.PNG)
![捕获](https://user-images.githubusercontent.com/24732116/217513104-6a5e9804-f23f-4589-bbd8-d73dbca39cad.PNG)

**Comment by Tom60chat** [comment] 2023-02-08 19:41
That odd, can you try to:
 - Delete the session folder
 - Use the built-in browser with `-br built-in` argument
 
If this is still not working, can you share me your user agent (https://www.whatismybrowser.com/detect/what-is-my-user-agent/)

**Comment by 12189108** [comment] 2023-02-11 09:14
This still doesn't work after using the method you provided, here is my browser UA: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36”

**Comment by 12189108** [comment] 2023-02-11 09:20
At the same time, it was also found that after switching to other regions through VPN, the mobile phone search task could not be completed. But on my phone switched UA to "Mozilla/5.0 (Linux; Android 10; HD1913) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.5481.63 Mobile Safari/537.36 EdgA/109.0.1518.70" works fine

**Comment by Tom60chat** [comment] 2023-02-11 10:26
Weird, I see other people from your country not having issue.

I don't know if this related to chrome, the app it's just telling chrome to accessing the website, with a custom UA witch look like yours.
it will be hard for me to know the reason.

**Comment by Octopustraveler** [comment] 2023-02-13 15:15
Can't login without VPN, I think  _Microsoft Rewards Farmer_  can only finished the task in another country (base on your vpn address) but China Bing have a different task method maybe?

So I think the problem is it can't finish China Bing rewards task (Can't login but when you login with VPN it will finish other country Bing task)

**Comment by 12189108** [comment] 2023-02-13 15:27
> Can't login without VPN, I think _Microsoft Rewards Farmer_ can only finished the task in another country (base on your vpn address) but China Bing have a different task method maybe?
> 
> So I think the problem is it can't finish China Bing rewards task (Can't login but when you login with VPN it will finish another country Bing task leaving China Bing task undone)
> 
> Maybe it'll be work out if you can login without VPN when you in China
I can log in to Bing Rewards without using a VPN, but it says not available when I use an automated program. There is no good workaround but to do the task manually (without using a VPN).

**Comment by 12189108** [comment] 2023-02-13 15:28
> Can't login without VPN, I think _Microsoft Rewards Farmer_ can only finished the task in another country (base on your vpn address) but China Bing have a different task method maybe?
> 
> So I think the problem is it can't finish China Bing rewards task (Can't login but when you login with VPN it will finish another country Bing task leaving China Bing task undone)
> 
> Maybe it'll be work out if you can login without VPN when you in China

I can log in to Bing Rewards without using a VPN, but it says not available when I use an automated program. There is no good workaround but to do the task manually (without using a VPN).

**Comment by Octopustraveler** [comment] 2023-02-13 15:38
> > Can't login without VPN, I think _Microsoft Rewards Farmer_ can only finished the task in another country (base on your vpn address) but China Bing have a different task method maybe?
> > So I think the problem is it can't finish China Bing rewards task (Can't login but when you login with VPN it will finish another country Bing task leaving China Bing task undone)
> > Maybe it'll be work out if you can login without VPN when you in China
> 
> I can log in to Bing Rewards without using a VPN, but it says not available when I use an automated program. There is no good workaround but to do the task manually (without using a VPN).

I mean we can't login in the automated program without VPN,  sure we all can login to Bing Rewards😂 it's China Bing and we both in China afterall

**Comment by Octopustraveler** [comment] 2023-02-14 03:37
> 

Still can't, it says:  `[Exception] Farmer - Can't sign in to Microsoft Rewards`

**Comment by 12189108** [comment] 2023-02-14 20:01
I may know the reason for the error, in China, you can't visit the rewards page directly, but you can access it after logging in, your program does not visit the rewards page without cookies (the first two visits to the page)

**Comment by lostliam** [comment] 2023-02-15 08:40
As an user in china, I meet the same problem.
use -nh shows that Service is not supported in this country.
But we will not have this limit if don't use this Farmer.
Thankyou and hope you can solve this problem!

**Comment by lostliam** [comment] 2023-02-15 08:54
> I may know the reason for the error, in China, you can't visit the rewards page directly, but you can access it after logging in, your program does not visit the rewards page without cookies (the first two visits to the page)

yes, in china, just directly view rewards.bing.com without cookies will show the message ' service not supported '
could you please adjust the steps of selenium?
Login first and then do other things.

**Comment by Tom60chat** [comment] 2023-02-15 09:24
Thanks for your investigation, I will try on my side to make the require fix, and hoping he will fix your issue.

**Comment by pan8664716** [comment] 2023-02-15 09:31
GoToMicrosoftRewardsPageAsync：

In China open https://rewards.bing.com/welcome the link will report an error;

In China needs to jump directly to https://rewards.bing.com/?sign=1

You can modify the code：

**TheFarm\MsRewards.cs GoToMicrosoftRewardsPageAsync method**
```
        public async Task GoToMicrosoftRewardsPageAsync()
        {
            while (!farmer.MainPage!.Url.StartsWith(url) || farmer.MainPage!.Url.StartsWith(url + "pointsbreakdown")) // Network issue, you know
            {
                await farmer.MainPage!.TryGoToAsync(url + "welcome", WaitUntilNavigation.Networkidle0);

                // Bruteforce this page
                while (farmer.MainPage!.Url.StartsWith(url + "welcome"))
                {
                    if (await farmer.MainPage!.QuerySelectorAsync("#start-earning-rewards-link") != null) // Sign up (or sign in)
                    {
                        // Wait the button to be enabled
                        await farmer.MainPage!.WaitForSelectorToHideAsync("a[id=\"start-earning-rewards-link\"][disabled=\"disabled\"]");

                        // If cookies, delete it!
                        if (await farmer.MainPage!.QuerySelectorAsync("#wcpConsentBannerCtrl") != null)
                            await farmer.MainPage!.RemoveAsync("#wcpConsentBannerCtrl");

                        // Click on the "Sign up to Rewards" link (Name can't be wrong I have the french version so...)
                        await farmer.MainPage!.ClickAsync("#start-earning-rewards-link");
                        await farmer.MainPage!.WaitForSelectorToHideAsync("#start-earning-rewards-link", false, 2000);
                    }
                    else // Weird... (Maybe network, it's always network)
                    {
                        throw new Exception(Resources.MsRewards.SignIn_Error);
                    }
                }
            }

            await farmer.MainPage.WaitTillHTMLRendered();

            // Check if the account has not been ban
            if (await farmer.MainPage.QuerySelectorAsync("#error") != null)
                await GetRewardsErrorAsync();
        }
```
需要修改成
```
        public async Task GoToMicrosoftRewardsPageAsync()
        {
            while (!farmer.MainPage!.Url.StartsWith(url) || farmer.MainPage!.Url.StartsWith(url + "pointsbreakdown")) // Network issue, you know
            {
                await farmer.MainPage!.TryGoToAsync(url + "?signin=1", WaitUntilNavigation.Networkidle0);

                // Bruteforce this page
                while (farmer.MainPage!.Url.StartsWith(url + ""))
                {
                    // select <div class="rewardsContent" , if it's not null it's because the page is loaded
                    if (await farmer.MainPage!.QuerySelectorAsync("div[class=\"rewardsContent\"]") != null)
                    {
                        break;
                    }
                }
            }

            await farmer.MainPage.WaitTillHTMLRendered();

            // Check if the account has not been ban
            if (await farmer.MainPage.QuerySelectorAsync("#error") != null)
                await GetRewardsErrorAsync();
        }
```

**Comment by Tom60chat** [comment] 2023-02-15 12:46
@pan8664716 This looks promising, thanks.

**Comment by SeaYJ** [comment] 2023-02-17 08:50
> In China open https://rewards.bing.com/welcome the link will report an error;
> 
> In China needs to jump directly to https://rewards.bing.com/?sign=1
> 
> You can modify the code：
> 
> **TheFarm\MsRewards.cs GoToMicrosoftRewardsPageAsync method**
> 
> ```
>         public async Task GoToMicrosoftRewardsPageAsync()
>         {
>             while (!farmer.MainPage!.Url.StartsWith(url) || farmer.MainPage!.Url.StartsWith(url + "pointsbreakdown")) // Network issue, you know
>             {
>                 await farmer.MainPage!.TryGoToAsync(url + "welcome", WaitUntilNavigation.Networkidle0);
> 
>                 // Bruteforce this page
>                 while (farmer.MainPage!.Url.StartsWith(url + "welcome"))
>                 {
>                     if (await farmer.MainPage!.QuerySelectorAsync("#start-earning-rewards-link") != null) // Sign up (or sign in)
>                     {
>                         // Wait the button to be enabled
>                         await farmer.MainPage!.WaitForSelectorToHideAsync("a[id=\"start-earning-rewards-link\"][disabled=\"disabled\"]");
> 
>                         // If cookies, delete it!
>                         if (await farmer.MainPage!.QuerySelectorAsync("#wcpConsentBannerCtrl") != null)
>                             await farmer.MainPage!.RemoveAsync("#wcpConsentBannerCtrl");
> 
>                         // Click on the "Sign up to Rewards" link (Name can't be wrong I have the french version so...)
>                         await farmer.MainPage!.ClickAsync("#start-earning-rewards-link");
>                         await farmer.MainPage!.WaitForSelectorToHideAsync("#start-earning-rewards-link", false, 2000);
>                     }
>                     else // Weird... (Maybe network, it's always network)
>                     {
>                         throw new Exception(Resources.MsRewards.SignIn_Error);
>                     }
>                 }
>             }
> 
>             await farmer.MainPage.WaitTillHTMLRendered();
> 
>             // Check if the account has not been ban
>             if (await farmer.MainPage.QuerySelectorAsync("#error") != null)
>                 await GetRewardsErrorAsync();
>         }
> ```
> 
> update to
> 
> ```
>         public async Task GoToMicrosoftRewardsPageAsync()
>         {
>             while (!farmer.MainPage!.Url.StartsWith(url) || farmer.MainPage!.Url.StartsWith(url + "pointsbreakdown")) // Network issue, you know
>             {
>                 await farmer.MainPage!.TryGoToAsync(url + "?signin=1", WaitUntilNavigation.Networkidle0);
> 
>                 // Bruteforce this page
>                 while (farmer.MainPage!.Url.StartsWith(url + ""))
>                 {
>                     // select <div class="rewardsContent" , if it's not null it's because the page is loaded
>                     if (await farmer.MainPage!.QuerySelectorAsync("div[class=\"rewardsContent\"]") != null)
>                     {
>                         break;
>                     }
>                 }
>             }
> 
>             await farmer.MainPage.WaitTillHTMLRendered();
> 
>             // Check if the account has not been ban
>             if (await farmer.MainPage.QuerySelectorAsync("#error") != null)
>                 await GetRewardsErrorAsync();
>         }
> ```

Nice,maybe this is the right way!

**Comment by chgmqh** [comment] 2023-02-21 03:27
so, if jump directly to https://rewards.bing.com/?sign=1 is work, can anyone upload a new exe file ？ thanks.

**Comment by Tom60chat** [comment] 2023-02-22 13:55
I'm going to let the issue open, until the fix as been pushed into a release version.

**Comment by blover2009** [comment] 2023-03-03 06:07
> In China open https://rewards.bing.com/welcome the link will report an error;
> 
> In China needs to jump directly to https://rewards.bing.com/?sign=1
> 
> You can modify the code：
> 
> **TheFarm\MsRewards.cs GoToMicrosoftRewardsPageAsync method**
> 
> ```
>         public async Task GoToMicrosoftRewardsPageAsync()
>         {
>             while (!farmer.MainPage!.Url.StartsWith(url) || farmer.MainPage!.Url.StartsWith(url + "pointsbreakdown")) // Network issue, you know
>             {
>                 await farmer.MainPage!.TryGoToAsync(url + "welcome", WaitUntilNavigation.Networkidle0);
> 
>                 // Bruteforce this page
>                 while (farmer.MainPage!.Url.StartsWith(url + "welcome"))
>                 {
>                     if (await farmer.MainPage!.QuerySelectorAsync("#start-earning-rewards-link") != null) // Sign up (or sign in)
>                     {
>                         // Wait the button to be enabled
>                         await farmer.MainPage!.WaitForSelectorToHideAsync("a[id=\"start-earning-rewards-link\"][disabled=\"disabled\"]");
> 
>                         // If cookies, delete it!
>                         if (await farmer.MainPage!.QuerySelectorAsync("#wcpConsentBannerCtrl") != null)
>                             await farmer.MainPage!.RemoveAsync("#wcpConsentBannerCtrl");
> 
>                         // Click on the "Sign up to Rewards" link (Name can't be wrong I have the french version so...)
>                         await farmer.MainPage!.ClickAsync("#start-earning-rewards-link");
>                         await farmer.MainPage!.WaitForSelectorToHideAsync("#start-earning-rewards-link", false, 2000);
>                     }
>                     else // Weird... (Maybe network, it's always network)
>                     {
>                         throw new Exception(Resources.MsRewards.SignIn_Error);
>                     }
>                 }
>             }
> 
>             await farmer.MainPage.WaitTillHTMLRendered();
> 
>             // Check if the account has not been ban
>             if (await farmer.MainPage.QuerySelectorAsync("#error") != null)
>                 await GetRewardsErrorAsync();
>         }
> ```
> 
> update to
> 
> ```
>         public async Task GoToMicrosoftRewardsPageAsync()
>         {
>             while (!farmer.MainPage!.Url.StartsWith(url) || farmer.MainPage!.Url.StartsWith(url + "pointsbreakdown")) // Network issue, you know
>             {
>                 await farmer.MainPage!.TryGoToAsync(url + "?signin=1", WaitUntilNavigation.Networkidle0);
> 
>                 // Bruteforce this page
>                 while (farmer.MainPage!.Url.StartsWith(url + ""))
>                 {
>                     // select <div class="rewardsContent" , if it's not null it's because the page is loaded
>                     if (await farmer.MainPage!.QuerySelectorAsync("div[class=\"rewardsContent\"]") != null)
>                     {
>                         break;
>                     }
>                 }
>             }
> 
>             await farmer.MainPage.WaitTillHTMLRendered();
> 
>             // Check if the account has not been ban
>             if (await farmer.MainPage.QuerySelectorAsync("#error") != null)
>                 await GetRewardsErrorAsync();
>         }
> ```

So, how to do it, these codes are updated to that file, thank you

**Comment by Tom60chat** [comment] 2023-03-17 16:38
Hello, Sorry I forgot you, I hope I haven't kept you waiting too long.

Version 0.10.1 is out, I invite you to test this version.

You can get it at the following address: https://github.com/Tom60chat/Microsoft-Rewards-Farmer-Sharp/releases/tag/v0.10.1-beta1

If will close this issue, you can reopen it if the issue is still happening.

**Closed by Tom60chat** 2023-03-17 16:38 UTC
Labels: help wanted, microsoft
