### ISSUE TITLE
a bug with -n parameter

### ISSUE THREAD

**Issue by danding-s** [Tom60chat/Microsoft-Rewards-Farmer-Sharp#156] opened 2023-04-19 06:48 UTC
when i run exe with -n parameter，the error must appear 。

version：0.9.2

Unhandled exception. System.AggregateException: One or more errors occurred. (The value must be greater than or equal to zero and less than the console's buffer size in that dimension. (Parameter 'top')

**Comment by Tom60chat** [comment] 2023-05-20 15:23
Duplicate of #118

**Closed by Tom60chat** 2023-05-20 15:23 UTC
Labels: bug
