### ISSUE TITLE
CodeBase Error on Debian 11 x64

### ISSUE THREAD

**Issue by PianCat** [Tom60chat/Microsoft-Rewards-Farmer-Sharp#158] opened 2023-04-24 06:58 UTC
**Describe the bug**
When attempting to run the "Microsoft Rewards Farmer.TUI" executable on Debian 11 x64, I encountered the following error:

```
Unhandled exception.
System.AggregateException: One or more errors occurred. (CodeBase is not supported on assemblies loaded from a single-file bundle.)
 ---> System.NotSupportedException: CodeBase is not supported on assemblies loaded from a single-file bundle.
   at System.Reflection.RuntimeAssembly.get_CodeBase()
   at PuppeteerSharp.BrowserFetcher.GetExecutablePath() in C:\projects\puppeteer-sharp\lib\PuppeteerSharp\BrowserFetcher.cs:line 356
   at PuppeteerSharp.BrowserFetcher..ctor() in C:\projects\puppeteer-sharp\lib\PuppeteerSharp\BrowserFetcher.cs:line 53
   at PuppeteerPlus.Utility.TryGetBuildInBrowser(String& browserPath) in /home/tom/Documents/Projets/Logiciels/Microsoft-Rewards-Farmer-Sharp/Puppeteer Plus/Utility.cs:line 129
   at MicrosoftRewardsFarmer.Utilities.PuppeteerPlusUtility.GetBrowserAsync() in /home/tom/Documents/Projets/Logiciels/Microsoft-Rewards-Farmer-Sharp/Microsoft Rewards Farmer/Utilities/PuppeteerPlusUtility.cs:line 34
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean )
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean )
   at System.Threading.Tasks.Task`1.get_Result()
   at MicrosoftRewardsFarmer.TUI.Program.StartFarming() in /home/tom/Documents/Projets/Logiciels/Microsoft-Rewards-Farmer-Sharp/Microsoft Rewards Farmer.TUI/Program.cs:line 90
   at MicrosoftRewardsFarmer.TUI.Program.Main(String[] args) in /home/tom/Documents/Projets/Logiciels/Microsoft-Rewards-Farmer-Sharp/Microsoft Rewards Farmer.TUI/Program.cs:line 60

Press any key to exit.
```

**To Reproduce**
1. Download the linux-x64.zip file from https://github.com/Tom60chat/Microsoft-Rewards-Farmer-Sharp/releases/tag/v0.10.1-beta1
2. Unzip the file
3. Run the "Microsoft Rewards Farmer.TUI" executable
4. See the error

**Expected behavior**
I expected the "Microsoft Rewards Farmer.TUI" program to run without error.

**Screenshots**
![Snipaste_2023-04-24_14-53-16](https://user-images.githubusercontent.com/50688679/233920845-a6098db1-e914-4b78-934a-98afe2e8be28.png)

**Additional context**
I am running Debian 11 x64. 

Logs file located in Logs folder:
[2023-04-24 14.57.01.txt](https://github.com/Tom60chat/Microsoft-Rewards-Farmer-Sharp/files/11307549/2023-04-24.14.57.01.txt)

**Comment by Tom60chat** [comment] 2023-05-20 15:27
I like the effort you took to write this issue, unfortunately you should have looked if it already existed.
Duplicate of #126

**Closed by Tom60chat** 2023-05-20 15:27 UTC
Labels: bug
