### ISSUE TITLE
App closes itself after initialization

### ISSUE THREAD

**Issue by AdicoS99** [Tom60chat/Microsoft-Rewards-Farmer-Sharp#129] opened 2023-03-22 08:32 UTC
I am completely oblivious to programming stuff etc.. so I have no clue what the problem might be but whenever I open the app this pops up

![image](https://user-images.githubusercontent.com/36305058/226843773-3ce600ae-5251-442f-b7b4-aab0195006a5.png)

And after that the app just closes itself.

**Comment by baff3r** [comment] 2023-03-22 09:11
same error

**Comment by CrazyLight21** [comment] 2023-03-22 14:44
> I am completely oblivious to programming stuff etc.. so I have no clue what the problem might be but whenever I open the app this pops up
> 
> ![image](https://user-images.githubusercontent.com/36305058/226843773-3ce600ae-5251-442f-b7b4-aab0195006a5.png)
> 
> And after that the app just closes itself.

dup of #119

**Comment by Tom60chat** [comment] 2023-05-20 14:45
@CrazyLight21 Indeed, duplicate of #119.

**Closed by Tom60chat** 2023-05-20 14:45 UTC
Labels: bug
