### ISSUE TITLE
Unable to complete the search task on the mobile end

### ISSUE THREAD

**Issue by YiGang-Grapefruit** [Tom60chat/Microsoft-Rewards-Farmer-Sharp#160] opened 2023-04-26 17:05 UTC
After running the program, other search tasks can be completed, but the mobile search task cannot be completed at all times
![image](https://user-images.githubusercontent.com/63415204/234650171-c4c6c33c-18a8-47ad-808d-7069e19410a8.png)

**Comment by cqjerry** [comment] 2023-04-27 12:18
same problem

**Comment by CN-Patrick** [comment] 2023-04-28 10:03
i have same problem,

**Comment by windskyxb** [comment] 2023-04-29 02:59
Similarly, I also have the same problem

**Comment by DarkEnergy666** [comment] 2023-05-03 05:14
See issue# 110 [one of the last post]
This should fix the problem.

**Comment by windskyxb** [comment] 2023-05-06 01:16
> See issue# 110 [one of the last post] This should fix the problem.

Following this method of operation, it initially returned to normal, but after a few days, this problem will reappear

**Comment by Tom60chat** [comment] 2023-05-20 15:29
Duplicate of #110

**Closed by Tom60chat** 2023-05-20 15:29 UTC
Labels: bug
