### ISSUE TITLE
Error when running in Manjaro Linux

### ISSUE THREAD

**Issue by Suffice5815** [Tom60chat/Microsoft-Rewards-Farmer-Sharp#138] opened 2023-03-29 16:28 UTC
~/Downloads/linux-x64:  ./"Microsoft Rewards Farmer.TUI"

Unhandled exception.
System.AggregateException: One or more errors occurred. (CodeBase is not supported on assemblies loaded from a single-file bundle.)
 ---> System.NotSupportedException: CodeBase is not supported on assemblies loaded from a single-file bundle.
   at System.Reflection.RuntimeAssembly.get_CodeBase()
   at PuppeteerSharp.BrowserFetcher.GetExecutablePath() in C:\projects\puppeteer-sharp\lib\PuppeteerSharp\BrowserFetcher.cs:line 356
   at PuppeteerSharp.BrowserFetcher..ctor() in C:\projects\puppeteer-sharp\lib\PuppeteerSharp\BrowserFetcher.cs:line 53
   at PuppeteerPlus.Utility.TryGetBuildInBrowser(String& browserPath) in /home/tom/Documents/Projets/Logiciels/Microsoft-Rewards-Farmer-Sharp/Puppeteer Plus/Utility.cs:line 129
   at MicrosoftRewardsFarmer.Utilities.PuppeteerPlusUtility.GetBrowserAsync() in /home/tom/Documents/Projets/Logiciels/Microsoft-Rewards-Farmer-Sharp/Microsoft Rewards Farmer/Utilities/PuppeteerPlusUtility.cs:line 34
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean )
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean )
   at System.Threading.Tasks.Task`1.get_Result()
   at MicrosoftRewardsFarmer.TUI.Program.StartFarming() in /home/tom/Documents/Projets/Logiciels/Microsoft-Rewards-Farmer-Sharp/Microsoft Rewards Farmer.TUI/Program.cs:line 90
   at MicrosoftRewardsFarmer.TUI.Program.Main(String[] args) in /home/tom/Documents/Projets/Logiciels/Microsoft-Rewards-Farmer-Sharp/Microsoft Rewards Farmer.TUI/Program.cs:line 60

Press any key to exit.

**Comment by Suffice5815** [comment] 2023-03-29 16:46
I have .NET installed:

dotnet-host 7.0.2.sdk102-2
dotnet-runtime 7.0.2.sdk102-2
dotnet-sdk 7.0.2.sdk102-2

**Comment by Suffice5815** [comment] 2023-03-29 17:05
This is what happens when I try building it from source on VSCode:

/home/admin/Downloads/Microsoft-Rewards-Farmer-Sharp-master/Microsoft Rewards Farmer.TUI/Microsoft Rewards Farmer.TUI.csproj(27,9): warning : Microsoft Rewards Farmer.TUI.csproj is Multilingual build enabled, but the Multilingual App Toolkit is unavailable during the build. If building with Visual Studio, please check to ensure that toolkit is properly installed.
/home/admin/Downloads/Microsoft-Rewards-Farmer-Sharp-master/Puppeteer Plus/Extensions.cs(291,39): warning CS0168: The variable "e" is declared but never used [/home/admin/Downloads/Microsoft-Rewards-Farmer-Sharp-master/Puppeteer Plus/Puppeteer Plus.csproj]
/home/admin/Downloads/Microsoft-Rewards-Farmer-Sharp-master/Puppeteer Plus/Extensions.cs(351,9): warning CS8602: Dereferencing a possibly null reference. [/home/admin/Downloads/Microsoft-Rewards-Farmer-Sharp-master/Puppeteer Plus/Puppeteer Plus.csproj]
/home/admin/Downloads/Microsoft-Rewards-Farmer-Sharp-master/Microsoft Rewards Farmer/MsRewards.cs(36,15): warning CS0618: "PuppeteerExtensions.WaitTillHTMLRenderedAsync(IPage, int)" is obsolete: "This method is slower, and not efficient. Use WaitForPageToLoadAsync() instead." [/home/admin/Downloads/Microsoft-Rewards-Farmer-Sharp-master/Microsoft Rewards Farmer/Microsoft Rewards Farmer.csproj]
/home/admin/Downloads/Microsoft-Rewards-Farmer-Sharp-master/Microsoft Rewards Farmer/Models/Settings.cs(44,28): warning CS0618: "Settings.GetSettingsJson(string)" is obsolete: "Json is not user friendly" [/home/admin/Downloads/Microsoft-Rewards-Farmer-Sharp-master/Microsoft Rewards Farmer/Microsoft Rewards Farmer.csproj]
/home/admin/Downloads/Microsoft-Rewards-Farmer-Sharp-master/Microsoft Rewards Farmer/Bing.cs(62,15): warning CS0618: "PuppeteerExtensions.WaitTillHTMLRenderedAsync(IPage, int)" is obsolete: "This method is slower, and not efficient. Use WaitForPageToLoadAsync() instead." [/home/admin/Downloads/Microsoft-Rewards-Farmer-Sharp-master/Microsoft Rewards Farmer/Microsoft Rewards Farmer.csproj]
/home/admin/Downloads/Microsoft-Rewards-Farmer-Sharp-master/Microsoft Rewards Farmer/MsRewards.cs(242,15): warning CS0618: "PuppeteerExtensions.WaitTillHTMLRenderedAsync(IPage, int)" is obsolete: "This method is slower, and not efficient. Use WaitForPageToLoadAsync() instead." [/home/admin/Downloads/Microsoft-Rewards-Farmer-Sharp-master/Microsoft Rewards Farmer/Microsoft Rewards Farmer.csproj]
/home/admin/Downloads/Microsoft-Rewards-Farmer-Sharp-master/Microsoft Rewards Farmer/Bing.cs(242,19): warning CS0618: "PuppeteerExtensions.WaitTillHTMLRenderedAsync(IPage, int)" is obsolete: "This method is slower, and not efficient. Use WaitForPageToLoadAsync() instead." [/home/admin/Downloads/Microsoft-Rewards-Farmer-Sharp-master/Microsoft Rewards Farmer/Microsoft Rewards Farmer.csproj]
/home/admin/Downloads/Microsoft-Rewards-Farmer-Sharp-master/Microsoft Rewards Farmer/Bing.cs(491,23): warning CS0618: "PuppeteerExtensions.WaitTillHTMLRenderedAsync(IPage, int)" is obsolete: "This method is slower, and not efficient. Use WaitForPageToLoadAsync() instead." [/home/admin/Downloads/Microsoft-Rewards-Farmer-Sharp-master/Microsoft Rewards Farmer/Microsoft Rewards Farmer.csproj]

**Comment by haq** [comment] 2023-03-31 19:30
You can ignore the warnings when building and the app should still run.

**Comment by Suffice5815** [comment] 2023-04-10 16:31
> You can ignore the warnings when building and the app should still run.

It doesn't run

**Comment by Tom60chat** [comment] 2023-05-20 08:46
Duplicate of #126

**Closed by Tom60chat** 2023-05-20 08:46 UTC
Labels: bug
